{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a9d20ac3-b46b-4d05-9b9a-1a92d898d39a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Ans no1\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"12feb.log\",level=logging.INFO,format='%(message)s %(asctime)s')\n",
    "logging.info(\"the first ans is writting now\")\n",
    "\n",
    "'''In Python, an exception is an event, during the execution of a program, \n",
    "that disrupts the normal flow of the program's instructions.\n",
    " Exceptions are raised when a program encounters an error condition,\n",
    "  such as division by zero or trying to access an index in a list that is out of range.\n",
    "\n",
    "The difference between exceptions and syntax errors is that syntax errors are errors in the code itself, \n",
    "such as a syntax mistake, a typo, or incorrect indentation, that prevent the code from running. \n",
    "On the other hand, exceptions are generated by the code that is already syntactically correct,\n",
    " but the execution of the code encounters an error condition, such as an arithmetic operation with invalid operands.\n",
    "\n",
    "Syntax errors are detected by the Python interpreter when the code is first parsed and will prevent the code from executing.\n",
    " On the other hand, exceptions are raised during the execution of the code and can be handled using try-except blocks,\n",
    "  allowing the program to continue running even if an error has occurred.'''\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "862fb8cc-8d81-48e3-948c-46918639a18c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter a 23\n",
      "enter b 0\n"
     ]
    },
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [9], line 10\u001b[0m\n\u001b[1;32m      8\u001b[0m a\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mint\u001b[39m(\u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124menter a\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[1;32m      9\u001b[0m b\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mint\u001b[39m(\u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124menter b\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m---> 10\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43ma\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[43mb\u001b[49m)\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# Ans no2\n",
    "\n",
    "logging.info(\"the 2ns ans is writting now\")\n",
    "\n",
    "'''When an exception is not handled in Python, the program will raise the uncaught exception and terminate immediately. \n",
    "This means that any subsequent code that was supposed to run will not be executed, and the program will stop working.'''\n",
    "\n",
    "#  example\n",
    "logging.info(\"abut exception\")\n",
    "a=int(input(\"enter a\"))\n",
    "b=int(input(\"enter b\"))\n",
    "print(a/b)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "52dacc7c-d7ec-41c3-9e83-938b60a3632e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "there is an exception in the code\n"
     ]
    }
   ],
   "source": [
    "# Ans no3\n",
    "\n",
    "logging.info(\"the 3rd ans is writting now\")\n",
    "\n",
    "''' the try and except statements are used to handle exceptions.'''\n",
    "# example\n",
    "\n",
    "logging.info(\"abut the try and except in q3\")\n",
    "\n",
    "try:\n",
    "    f=open(\"f.txt\",'r')\n",
    "except Exception as e:\n",
    "    print(\"there is an exception in the code\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "07445596-7b83-4103-a523-d7a19ff42142",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter age 223\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "age cant be grater than 200\n"
     ]
    }
   ],
   "source": [
    "# Ans no4\n",
    "\n",
    "logging.info(\"the 4rth ans is writting now\")\n",
    "\n",
    "'''try and else are use to handle the exception wich are generated on the execution of the code '''\n",
    "# example\n",
    "logging.info(\"abut the try and except\")\n",
    "a=int(input(\"enter a\")) #enter 34\n",
    "b=int(input(\"enter b\")) #enter 0\n",
    "print(a/b) # 34/0 will generate an exception\n",
    "\n",
    "\n",
    "''' finally is the exception handler whilch will execute in any situation \n",
    "'''\n",
    "# example2\n",
    "try :\n",
    "   f=open(\"asdf.txt\",'r')\n",
    "\n",
    "finally:\n",
    "    print(\"filnally will print in any situation\")\n",
    "\n",
    "'''The raise statement in Python is used to raise an exception. It allows to throw an error manually, \n",
    "which can be caught and handled by a try-except block. This can be useful in situations \n",
    "where you want to force an error to occur in your code to handle certain conditions.'''\n",
    "\n",
    "# example3\n",
    "\n",
    "logging.info(\"declaring the class for showing errors\")\n",
    "\n",
    "class valid (Exception):\n",
    "\n",
    "    def __init__(self, message) :\n",
    "        self.mess=message\n",
    "\n",
    "logging.info(\"declaring the function for taking input as age\") \n",
    "\n",
    "def validate(age):\n",
    "    if age<0:\n",
    "        raise valid(\"age cant be nagetive\")  \n",
    "    elif age>200:\n",
    "        raise valid(\"age cant be grater than 200\")         \n",
    "    else:\n",
    "        print(\"valid age\")\n",
    "        \n",
    "logging.info(\"use the exception handelers\")   \n",
    "     \n",
    "try:\n",
    "    a=int(input(\"enter age\"))\n",
    "    validate(a)\n",
    "except valid as v:\n",
    "    print(v)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1ebe719c-3d6a-4bab-bdbb-3d588e24d3b3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter age -654\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "age cant be nagetive\n"
     ]
    }
   ],
   "source": [
    "# Ans no5\n",
    "\n",
    "logging.info(\"the 5th ans is writting now\")\n",
    "\n",
    "'''Custom exceptions can be useful when you want to provide more meaningful error messages to the user,\n",
    " or to differentiate between different types of errors in your code. However,\n",
    "  it's important to use custom exceptions judiciously and only when it's necessary, \n",
    "  as they can make your code harder to understand and debug.\n",
    "\n",
    "  ustom exceptions in Python are user-defined exceptions that can be raised and caught in a try-except block \n",
    "  just like built-in exceptions. Custom exceptions allow you to add additional information to an exception\n",
    " and make it easier to understand the source and cause of the error in your code.\n",
    "\n",
    "'''\n",
    "# example\n",
    "# example3\n",
    "logging.info(\"declaring the class for showing errors\")\n",
    "\n",
    "class valid (Exception):\n",
    "\n",
    "    def __init__(self, message) :\n",
    "        self.mess=message\n",
    "\n",
    "logging.info(\"declaring the function for taking input as age\") \n",
    "\n",
    "def validate(age):\n",
    "    if age<0:\n",
    "        raise valid(\"age cant be nagetive\")  \n",
    "    elif age>200:\n",
    "        raise valid(\"age cant be grater than 200\")         \n",
    "    else:\n",
    "        print(\"valid age\")\n",
    "        \n",
    "logging.info(\"use the exception handelers\")     \n",
    "   \n",
    "try:\n",
    "    a=int(input(\"enter age\"))\n",
    "    validate(a)\n",
    "except valid as v:\n",
    "    print(v)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4d2078d3-5bce-4263-9efb-55b5f4b52f37",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter age 33\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "valid age\n"
     ]
    }
   ],
   "source": [
    "# Ans no6\n",
    "\n",
    "logging.info(\"the 6th ans is writting now\")\n",
    "\n",
    "logging.info(\"declaring the class for showing errors\")\n",
    "\n",
    "class valid (Exception):\n",
    "\n",
    "    def __init__(self, message) :\n",
    "        self.mess=message\n",
    "\n",
    "logging.info(\"declaring the function for taking input as age\") \n",
    "\n",
    "def validate(age):\n",
    "    if age<0:\n",
    "        raise valid(\"age cant be nagetive\")  \n",
    "    elif age>200:\n",
    "        raise valid(\"age cant be grater than 200\")         \n",
    "    else:\n",
    "        print(\"valid age\")\n",
    "        \n",
    "logging.info(\"use the exception handelers\")    \n",
    "    \n",
    "try:\n",
    "    a=int(input(\"enter age\"))\n",
    "    validate(a)\n",
    "except valid as v:\n",
    "    print(v)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c426fce2-b2d4-448d-b94d-0eb02a2ea135",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
